# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ "develop", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Run Build for 16 version
        if: matrix.node-version == '16.x'
        run: npm run build
      - name: Run Build for the recent version (17.x and 18.x)
        if: matrix.node-version != '16.x'
        run:
          export NODE_OPTIONS=--openssl-legacy-provider && npm run build
      - name: Run build of server-side
        uses: iCrawl/action-tsc@v1
        with:
          project: cookbook-server
